# Generated by Django 5.0.3 on 2024-03-29 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='name',
            new_name='nom',
        ),
    ]
