# Generated by Django 5.0.3 on 2024-04-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_rename_name_categories_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produit_images/'),
        ),
    ]
