# Generated by Django 5.0.3 on 2024-04-03 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0007_rename_token_tokenperso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TokenPerso',
        ),
    ]
